### PR TITLE
Add color picker & input type

### PR DESCRIPTION
**Pull request by InventivetalentDev**
Added color picker
  

Added an option to the text input to specify the input type (e.g. number, email, url, etc.)

### CODE REVIEW

**Comment by tkambler** [comment]
Very cool. Reviewing now.

**Comment by tkambler** [comment]
@InventivetalentDev I think this is a great idea - thanks! Would you be willing to update so that when presented with a color selection field, the input resembles the `SketchExample` [shown here](http://casesandberg.github.io/react-color/#examples)? Rather than being shown the full picker by default, you'd simply have a button showing the presently selected color. Clicking the button would then display the full picker.

Unrelated - The range slider that you included in your last PR seems to have brought in a weird artifact when contents flow off the edge of the screen. See the number that's hanging out in the bottom-right-hand corner of the screen?

**Comment by InventivetalentDev** [comment]
any updates on this? :)

**Comment by tkambler** [comment]
I’m traveling. Expect this to get merged on Monday. Thanks!

**Comment by tkambler** [comment]
Looking at this now.

**Comment by tkambler** [comment]
This looks great, @InventivetalentDev. Merging.

**Pull request merged**
