### PR TITLE
Add list type field

### PR DESCRIPTION
**Pull request by andytompkins**
This PR adds an orderable list type component.
screen shot 2018-08-08 at 5 24 59 pm

### CODE REVIEW

**Comment by andytompkins** [comment]
@tkambler what do you think? is this something you would want to add?

**Comment by tkambler** [comment]
Don't see any reason not to. Give me at least a day or two to get this merged in, I'm super busy at the moment. But it will get done.

**Comment by andytompkins** [comment]
No problem, take your time! I totally understand, just wasn't sure if you had noticed the PR or not.

**Comment by andytompkins** [comment]
Hey, any chance you could merge this soon? :)

**Comment by tkambler** [comment]
Today. :)

**Comment by tkambler** [comment]
@andytompkins Meet me [over here](https://github.com/tkambler/electron-preferences/pull/8).

**Pull request closed without merging**
