### PR TITLE
Fix Accelerator

### LINKED ISSUE #66: Accelerator setting is incorrect
This should be `alt+p`: 
image

As always, probably better to use a library like mousetrap or hotkey.js for this.

### PR DESCRIPTION
**Pull request by lacymorrow**
- Rewrite as a functional component
- Use a lookup + a little creative liberties from myself to exclude some values from being set.
- Add an option for `accelerator` components: `modifierRequired`. By default a single key can be set like `P`, if `modifierRequired` is true keys must be provided alongside a modifier like `Shift`+`P`

Fix #66

### CODE REVIEW

**Comment by lacymorrow** [comment]
@pvrobays pretty please :)

**Comment by pvrobays** [comment]
@lacymorrow Looks good, ready to be merged once conflicts have been resolved!

**Comment by lacymorrow** [comment]
Good to go 👍

**Comment by pvrobays** [comment]
Thanks for the contribution!

**Pull request merged**
