### PR TITLE
Create new event `onPreferencesUpdated` 

### PR DESCRIPTION
**Pull request by lvcabral**
New event created to allow the application to react when preferences are updated.
Implements #213

### CODE REVIEW

**Comment by pvrobays** [comment]
Hi @lvcabral 
Thanks for the PR!

So -if I understand correctly- this would provide the preferences window to pass on a handler which gets triggered when the preferences are updated.
However, right now there's no use case that the preferences window needs to be updated of preferences changes I think?
What is your use case that you want this new event exposed on the preferences window?

**Comment by lvcabral** [comment]
@pvrobays my use case is have configurable themes on the settings screen, I allow my users to pick 4 options: purple, dark, light and system, to accomplish that I had to make 2 changes:

1. This one to allow register to the event
2. A custom `index.html` (see code below)

I first pushed this change, and if approved I would ask for a way to customize the asset `index.html` or somehow have a way to inject a script on this file, just like we can customize the `css`.

image

**Comment by lacymorrow** [comment]
Interesting! Looks fine from here.

**Comment by pvrobays** [comment]
Looks cool! There is a feature request open to enable custom themes, but I like the workaround you found.

Not sure if there are many more use cases for this event other than setting the theme of the prefs window, but I'll definitely approve it.

Would you mind creating an issue for this, referencing it to this PR, and adding a line to the Changelog.md? I'll merge it afterwards.

**Comment by lvcabral** [comment]
Created issue, updated the `changelog` (the linter added lines between the titles to match .md standard) and the name of the event to match your naming standard (...Changed -> ...Updated)

**Review by lacymorrow — APPROVED** [review]
Woot woot, LGTM++

**Comment by lacymorrow** [comment]
I won't punish you by holding up this PR any longer, but we do need to document the API in the readme a LOT better than it is currently.

**Comment by lvcabral** [comment]
@lacymorrow do you want me to update the Readme too? This was not clear in your message above.

**Review by lacymorrow — APPROVED** [review]

**Pull request merged**
