### PR TITLE
Allow overriding browser window's title

### LINKED ISSUE #23: BrowserWindow's title can't be overriden
If we set

```
new ElectronPreferences({
  dataStore: path.resolve(__dirname, 'preferences.json'),
  defaults: {
    markdown: {
      auto_format_links: true,
      show_gutter: false,
    },
    preview: {
      show: true,
    },
    drawer: {
      show: true,
    },
  },
  webPreferences: {
    devTools: false,
  },
  browserWindowOverrides: {
    title: 'Another thing',
  },
}
```

The `title`option gets ignored, this is because according to the [BrowserWindow](https://electronjs.org/docs/api/browser-window) docs

>title String (optional) - Default window title. Default is "Electron". If the HTML tag <title> is defined in the HTML file loaded by loadURL(), this property will be ignored.

And the `index.html` of the build has the `title` property defined

```
<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8">
        <title>Preferences</title>
        <link rel="stylesheet" href="style.css">
        <link rel="stylesheet" href="css/vendor.css">
    </head>
    <body>
        <div class="window noselect" id="window"></div>
        <script src="js/vendor.js"></script>
        <script src="js/app.bundle.js"></script>
    </body>
</html>
```

Removing `<title>Preferences</title>` should be enough

### PR DESCRIPTION
**Pull request by ednjv**
closes #23

### CODE REVIEW

**Comment by tkambler** [comment]
If you'll update this so that a default page title of _Preferences_ is set via the API, I'll approve and merge.

**Comment by ednjv** [comment]
@tkambler not sure what you mean, but right now this the default title if you don't set anything:

https://github.com/tkambler/electron-preferences/blob/master/index.js#L162

**Comment by ednjv** [comment]
hey @tkambler please check my last commit, maybe this is what you want? I'll update the readme if so :)

**Comment by ednjv** [comment]
some examples:

```
preferences.browserWindowOverride('webPreferences', {devTools: true})
preferences.browserWindowOverride('title', 'My new title')
```

**Comment by pvrobays** [comment]
Created an new PR for this

**Pull request closed without merging**
