### PR TITLE
Feature/accesibility

### LINKED ISSUE #76: Accessibility issues
This tool is very very nice, thanks for building it.

Although, it has serious accessibility issues.

The placeholders are quite invisible:

This foreground (#BDC2C9) with that background (#E7E7E7) gives a contrast ratio of 1.44:1 (it should be at least 4.5:1) See it [here](https://webaim.org/resources/contrastchecker/?fcolor=BDC2C9&bcolor=E7E7E7).

Happens the same in Dark mode

It has slightly a better contrast ratio (2.32:1) as seen [here](https://webaim.org/resources/contrastchecker/?fcolor=5D5D5D&bcolor=252525)

----

The inputs (text, dropdown, list, perhaps more)  have no label so if a blind user tabs into it, it won't say what its supposed to be put in there.

One solution (easier one) is to change the `div` you have as a label for a proper label and then use `htmlFor` and an `id`. Another one, in certain cases is to use `aria-describedby` and point it to the help message.

----

There is no way to move to the preferences sidebar with the keyboard alone.

----

Perhaps there are more, and I understand this is always problematic, but I believe your library is really nice but this issues will prevent a good majority of apps from using it. There are laws that enforces companies to do it and this will discard electron-preferences.

### PR DESCRIPTION
**Pull request by pvrobays**
Add accessibility features:

- [x] Tabbing through the side bar via `tab` and `arrow keys`
- [x] Improve contrast of text in the UI for the light as well as the dark theme
- [x] Label tabs, input and other form fields for blind people to have their narrator work
- [x] Add :focus styles to radio and checkbox forms

Other Todo's:
- [x] add info to the README
- [x] update CHANGELOG
- [x] test
- [x] find experts in the field who can give feedback (if possible. @Foxandxss maybe you can help here?)

Fixes #76

### CODE REVIEW

**Comment by lacymorrow** [comment]
Looks like we need `:focus` styles for some of the components, like the radio buttons: 
image

**Comment by lacymorrow** [comment]
I love what you've done, and it works well enough but I think there's a better approach here without resorting to using Javascript to control the tab order.

I think the better solution would be to use `<button>`s instead of `<div>`s for the sidebar buttons, then they will properly respond to keyboard inputs. We can add `tabindex="0"` on the components and the browser should be able to handle the rest.

**Comment by pvrobays** [comment]
@lacymorrow using tabindexes was my first thought of implementing it, until I found the following [article](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles/Tab_Role).
Apparently this is common practice and is what I think @Foxandxss ment in describing the issue. I am a complete newb in the field of accessibility, so any tips/common practices are welcome feedback!

**Comment by Foxandxss** [comment]
This is a huge step forward. Colors are way better now and at least I am able to move between sidebar and content.

There are some components that are still not tabable like the radio buttons, the slider...  Well only inputs seems to be tababble.

I like what I see!

**Comment by pvrobays** [comment]
@Foxandxss The radio buttons and slider should already be tab-able, however the UI doesn't highlight them. I'll still fix that.
I might skip the 'color' input, as I would have no idea on how to go about and make that accessible only via keyboard input.
I'll keep you posted when more accessibility features have been added to the PR.

Did the side bar navigation with keyboard works as you would've expected?

**Comment by lacymorrow** [comment]
@pvrobays I see what you're saying now with using tabindexes with non-visible content may not work. In that case I think your solution is elegant and seems to work great from my end.

One comment, it may make more sense for the orange focus `outline` for the tabbing highlight in the sidebar to match the same blue as the outline for the components receiving focus

**Comment by pvrobays** [comment]
@lacymorrow The orange outline is indeed a good point. I'll keep it in mind when I continue working on this.

**Review by lacymorrow — APPROVED** [review]
LGTM++

**Comment by pvrobays** [comment]
@Foxandxss I think most of the functionality is ready?
Only thing left is `Label tabs, input and other form fields for blind people to have their narrator work`. Any tips on the best practices here?

Any feedback is welcome.

**Pull request merged**
