### PR TITLE
Adding a new preference will set a default value

### LINKED ISSUE #25: Adding a new preference doesn't add a default value unless you delete the preference file
I added a new preference under `defaults` and then proceded to add its corresponding section.

After I started my application again I noticed the default value wasn't set

So instead of this:
```
{
    "myNewPref": {
        "myNewOption": true
    },
    "client": {
        "name": "Wilson"
    }
}
```

I got this:
```
{
    "client": {
        "name": "Wilson"
    }
}
```

I shouldn't need to remove the file in order to get new preferences default values since I would loose my previous preferences

### PR DESCRIPTION
**Pull request by ednjv**
closes #25

### CODE REVIEW

**Comment by minter** [comment]
I ran across this same issue - any chance to get this merged in?

**Comment by ednjv** [comment]
@minter Yeah I wonder the same, it would be nice to have this merged

**Comment by jan-zajic** [comment]
Same. @tkambler can you, please, review this PR?

**Comment by pvrobays** [comment]
Thanks for the contribution. As @tkambler has a hard time creating time for this project I'll try to help out.

**Pull request merged**
