### PR TITLE
Andy Tompkins - List Type

### PR DESCRIPTION
**Pull request by tkambler**
Extends initial work done within [this PR](https://github.com/tkambler/electron-preferences/pull/7).

### CODE REVIEW

**Comment by andytompkins** [comment]
Thanks for the adjustments! :) Looks good to me.

**Comment by MisterTeacher** [comment]
Hi, when is this PR merged?  I'm looking forward to using list type field.
@andytompkins

**Comment by lacymorrow** [comment]
I probably wouldn't have used the modal, but I think this PR looks good and probably should be merged, can I get write access @pvrobays?

**Comment by pvrobays** [comment]
Yey, this one is finaly merged! 🎉
Thanks @andytompkins for the initial PR

Will be available in the next release

**Pull request merged**
